services:
  database:
    image: postgres:12.22 # Version explicite pour garantir la compatibilité
    container_name: postgres_database
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: products
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  adminer:
    image: adminer:4.8.1 # Version explicite
    container_name: adminer
    restart: always
    ports:
      - '8081:8080' # Adminer accessible via le port 8081
    environment:
      ADMINER_DEFAULT_SERVER: database # Correspond au service "database"
    networks:
      - app_network

volumes:
  postgres_data: # Volume nommé pour persister les données de la base de données
    driver: local

networks:
  app_network: # Réseau isolé pour les services
    driver: bridge
